import type { PortalData } from "./types";

export const demoData: PortalData = {
  resources: [
    {
      id: "r-1",
      name: "Marina Costa",
      email: "marina.costa@nexo.dev",
      role: "Senior Cloud Engineer",
      location: "São Paulo, SP",
      status: "Ativo",
      weeklyCapacity: 40,
      allocatedHours: 36,
      skills: [{ name: "Azure", level: 5 }, { name: "Terraform", level: 4 }, { name: "Kubernetes", level: 4 }],
    },
    {
      id: "r-2",
      name: "Rafael Martins",
      email: "rafael.martins@nexo.dev",
      role: "Power Platform Specialist",
      location: "Campinas, SP",
      status: "Ativo",
      weeklyCapacity: 40,
      allocatedHours: 28,
      skills: [{ name: "Power Apps", level: 5 }, { name: "Dataverse", level: 5 }, { name: "Copilot Studio", level: 4 }],
    },
    {
      id: "r-3",
      name: "Aline Rocha",
      email: "aline.rocha@nexo.dev",
      role: "Data Engineer",
      location: "Recife, PE",
      status: "Ativo",
      weeklyCapacity: 40,
      allocatedHours: 42,
      skills: [{ name: "Microsoft Fabric", level: 4 }, { name: "Python", level: 5 }, { name: "SQL", level: 5 }],
    },
    {
      id: "r-4",
      name: "Diego Nunes",
      email: "diego.nunes@nexo.dev",
      role: "Software Engineer",
      location: "Belo Horizonte, MG",
      status: "Férias",
      weeklyCapacity: 20,
      allocatedHours: 12,
      skills: [{ name: ".NET", level: 5 }, { name: "Azure", level: 3 }, { name: "React", level: 3 }],
    },
    {
      id: "r-5",
      name: "Beatriz Lima",
      email: "beatriz.lima@nexo.dev",
      role: "Cloud Architect",
      location: "Curitiba, PR",
      status: "Ativo",
      weeklyCapacity: 40,
      allocatedHours: 32,
      skills: [{ name: "Azure", level: 5 }, { name: "Architecture", level: 5 }, { name: "FinOps", level: 4 }],
    },
    {
      id: "r-6",
      name: "Lucas Freitas",
      email: "lucas.freitas@nexo.dev",
      role: "Junior Consultant",
      location: "Fortaleza, CE",
      status: "Ativo",
      weeklyCapacity: 40,
      allocatedHours: 16,
      skills: [{ name: "Azure", level: 2 }, { name: "Power BI", level: 3 }, { name: "SQL", level: 3 }],
    },
  ],
  clients: [
    {
      id: "cl-1",
      name: "Contoso Varejo",
      document: "12.345.678/0001-10",
      contactName: "Ana Souza",
      email: "ana@contoso.example",
      phone: "(11) 99999-1001",
      status: "Ativo",
      notes: "Operação nacional de varejo.",
    },
    {
      id: "cl-2",
      name: "Fabrikam Saúde",
      document: "23.456.789/0001-20",
      contactName: "Paulo Lima",
      email: "paulo@fabrikam.example",
      phone: "(11) 99999-1002",
      status: "Ativo",
      notes: "Conta de serviços gerenciados.",
    },
    {
      id: "cl-3",
      name: "Northwind Logística",
      document: "34.567.890/0001-30",
      contactName: "Carla Mendes",
      email: "carla@northwind.example",
      phone: "(21) 99999-1003",
      status: "Ativo",
      notes: "Programa de modernização de dados.",
    },
    {
      id: "cl-4",
      name: "Adventure Works",
      document: "45.678.901/0001-40",
      contactName: "Bruno Alves",
      email: "bruno@adventure.example",
      phone: "(41) 99999-1004",
      status: "Ativo",
      notes: "Advisory recorrente de cloud.",
    },
    {
      id: "cl-5",
      name: "Wide World Importers",
      document: "56.789.012/0001-50",
      contactName: "Luiza Rocha",
      email: "luiza@wideworld.example",
      phone: "(31) 99999-1005",
      status: "Ativo",
      notes: "Conta em fase de planejamento.",
    },
  ],
  engagements: [
    {
      id: "e-1",
      name: "Landing Zone Azure",
      clientId: "cl-1",
      client: "Contoso Varejo",
      type: "Projeto",
      status: "Em andamento",
      startDate: "2026-06-02",
      endDate: "2026-09-30",
      contractedHours: 720,
      consumedHours: 418,
      description: "Implantação da fundação cloud e governança de subscriptions.",
      allocations: [{ resourceId: "r-1", hours: 24 }, { resourceId: "r-5", hours: 16 }],
    },
    {
      id: "e-2",
      name: "Evolução Power Platform",
      clientId: "cl-2",
      client: "Fabrikam Saúde",
      type: "Serviço gerenciado",
      status: "Em andamento",
      startDate: "2026-01-10",
      endDate: "2026-12-20",
      contractedHours: 960,
      consumedHours: 646,
      description: "Sustentação e evolução mensal do portfólio de aplicações.",
      allocations: [{ resourceId: "r-2", hours: 28 }, { resourceId: "r-6", hours: 8 }],
    },
    {
      id: "e-3",
      name: "Data Hub Fabric",
      clientId: "cl-3",
      client: "Northwind Logística",
      type: "Projeto",
      status: "Em risco",
      startDate: "2026-04-15",
      endDate: "2026-08-22",
      contractedHours: 580,
      consumedHours: 487,
      description: "Modernização da plataforma analítica com Microsoft Fabric.",
      allocations: [{ resourceId: "r-3", hours: 42 }, { resourceId: "r-1", hours: 12 }],
    },
    {
      id: "e-4",
      name: "Cloud Advisory",
      clientId: "cl-4",
      client: "Adventure Works",
      type: "Serviço gerenciado",
      status: "Em andamento",
      startDate: "2026-03-01",
      endDate: "2027-02-28",
      contractedHours: 480,
      consumedHours: 172,
      description: "Aconselhamento técnico, FinOps e apoio à arquitetura.",
      allocations: [{ resourceId: "r-5", hours: 16 }, { resourceId: "r-4", hours: 12 }],
    },
    {
      id: "e-5",
      name: "Portal do Colaborador",
      clientId: "cl-5",
      client: "Wide World Importers",
      type: "Projeto",
      status: "Planejamento",
      startDate: "2026-08-03",
      endDate: "2026-11-27",
      contractedHours: 420,
      consumedHours: 0,
      description: "Novo portal interno integrado ao ecossistema Microsoft 365.",
      allocations: [{ resourceId: "r-4", hours: 20 }, { resourceId: "r-6", hours: 8 }],
    },
  ],
  certifications: [
    { id: "c-1", code: "AZ-305", name: "Azure Solutions Architect Expert", level: "Expert", renewalMonths: 12, holders: 2 },
    { id: "c-2", code: "AZ-104", name: "Azure Administrator Associate", level: "Associate", renewalMonths: 12, holders: 3 },
    { id: "c-3", code: "PL-600", name: "Power Platform Solution Architect Expert", level: "Expert", renewalMonths: 12, holders: 1 },
    { id: "c-4", code: "DP-600", name: "Fabric Analytics Engineer Associate", level: "Associate", renewalMonths: 12, holders: 2 },
    { id: "c-5", code: "AI-102", name: "Azure AI Engineer Associate", level: "Associate", renewalMonths: 12, holders: 1 },
    { id: "c-6", code: "SC-100", name: "Cybersecurity Architect Expert", level: "Expert", renewalMonths: 12, holders: 0 },
  ],
};
